### ISSUE TITLE
Deprecation warnings without deprecated code

### ISSUE THREAD

**Issue by tcrosen** [rackt/react-router#2795]
Hi folks, I just ran `npm install react-router@beta` as per Ryan's Tweet, which landed me `^2.0.0-rc3`.

I had deprecation warnings for some obvious problems.  I've since fixed them all, but I still get this warning 3 times:

```
Warning: [react-router] `props.history` and `context.history` are deprecated. Please use `context.router`. http://bit.ly/1mj4IZr
```

I'm trying it in a fairly small application and I am sure there are no remaining instances of `<anything>.history`.  I had 2 cases of this:

```js
this.props.history.pushState(null, '/dashboard');
```

which I switched to this:

```js
this.context.router.push('/dashboard');
```

**Comment by taion** [comment]
Drop a breakpoint there and see where it's getting called from?

**Comment by tcrosen** [comment]
The call stack wasn't even pointing to my code.  The culprit appears to be Webpack.  I tried webpack-dev-server instead of webpack-dev-middleware + express and the warnings went away.  I re-built the app a few times with webpack-dev-middleware and now the warnings are gone in both scenarios.  Cheers.

**Comment by tcrosen** [comment]
Just logging this for reference. The React Developer Tools Chrome extension is the source of the deprecation warnings.

**Comment by timdorr** [comment]
Ah, it's probably iterating over and accessing all props, including the deprecated ones. We had (have?) similar issues with PropTypes checks. Thanks for the update!

**Comment by adiachenko** [comment]
@timdorr Do you plan to address the issue before shipping 2.0-stable? I'm using webpack-dev-server and it doesn't seem like I can do anithing about these warnings beside disabling React Dev Tools. I understand that this is not entirely a problem on your end but still it somewhat bothers me.

**Comment by timdorr** [comment]
It's fixed in the next release.

**Comment by adiachenko** [comment]
@timdorr Thank you for the response, I feel much better now. :)

**Comment by chrisheninger** [comment]
Thanks @tcrosen, I was worried seeing it intermittently– tested your comment and realized it's dependent on whether or not I had accessed the React tab in dev tools.

Looking forward to the official release, thanks rackt team!

**Comment by neverfox** [comment]
@timdorr Next release of react-router or react-devtools? I'm still getting it with 2.0.0-rc4 and 0.4.13, respectively.

**Comment by timdorr** [comment]
Router

**Comment by rkovacevic** [comment]
If someone else gets here, I had the same problem with "react-router-bootstrap".

Solved by upgrading it to "^0.20.1"

**Comment by rossenv** [comment]
@rkovacevic +1 you save me a couple of hours

**Comment by worldlyjohn** [comment]
this worked for me -> [Upgrade to 2.0.0](https://github.com/reactjs/react-router/blob/master/upgrade-guides/v2.0.0.md#lifecycle-mixin)

```
  contextTypes: {
    router: React.PropTypes.object.isRequired
  },

```

**Comment by rodryquintero** [comment]
Are there any examples on how to user <RouterContext/> ?

**Comment by duhaime** [comment]
Like @tcrosen, I received the same warnings even though I wasn't requesting any `.history` data. The warnings only sprang inside the React dev tools (not the Chrome console), which made me suspicious. I upgraded the React dev tools to 2.0.11 and the warnings are gone.
